name: push
on:
  push:
    branches: 
    - main
jobs:
  build-container:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        run: docker image build . -t migelalfa/apitest:latest
    
      - name: Push the Docker image to the registry
        run: docker push migelalfa/apitest:latest
