name: push
on:
  push:
    branches: 
    - main
jobs:
  build-container:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Set up python
        uses: actions/setup-python@v2
      - name: Check
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: migelalfa/apitest
